version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: local.Dockerfile
    container_name: space_code
    command: ./script/start
    tty: true
    volumes:
      - .:/app
      - box:/box
    ports:
      - ${APP_PORT}:3000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: space_code-postgres
    ports:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: space_code_platform_development
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  box:
  postgres:
