#!/bin/bash

set -e

bundle check || BUNDLE_JOBS=4 bundle install

bin/rake db:create
bin/rake db:migrate
bin/rake db:seed

rm -f /app/tmp/pids/server.pid

echo "Starting..."

bin/rails s -p 3000 -b 0.0.0.0
